### ISSUE TITLE
MVP:  Sound Generator -> "AudioGen"

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v9-bears-team-11#1]
~~- [ ] Map Feature~~
~~- [ ] Filtering Feature~~
~~- [ ] API from the job listing providers~~

----

- [ ] CSS piano
- [ ] Web Audio API
- [ ] CSS Neon effects
- [ ] Generate mp3 or audio representation in code

**Comment by ghost** [comment]
What are epic points?

**Comment by paulywill** [comment]
Basically, an `Epic` is a release or project... so in this case, the voyage would be an epic I think.

https://www.zenhub.com/blog/how-to-use-epics-and-milestones/
